Play travis
Otus-DevOps-2022-02/emarking_infra pull request #2
Opened 2022-03-21 23:24 UTC by emarking

2022-03-22 07:04 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно починить тесты, оставил комментарий к файлу который нужно чинить
ДЗ возвращаю на доработку

2022-03-22 07:04 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Чиним тесты =)

2022-03-22 10:18 UTC, emarking commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
НЕ посмотерл)). Везде всегда подвох))

2022-03-22 10:20 UTC, emarking commented
Всё, исправил.

2022-03-23 07:46 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув =)

2022-03-23 08:27 UTC, emarking commented
HomeWork lesson 4

2022-03-23 08:27 UTC, merged